In [1]:
import numpy as np



In [2]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a1D)
print(a2D)





[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(np.arange(10))
# an array of evenly spaced values.


arr1 = np.arange(2, 10)
print(arr1)

arr2 = np.arange(1, 10, 2)
print(arr2)
# Create an array with a specified start, stop, and step values
np.arange(2, 10, dtype=np.int32)
# elements will be of type int32 (32-bit integer). not includes 10.

np.eye(3)
# 2d identity matrix

np.linspace(1., 4., 6)
x = np.arange(10)
print("x: ", x)
# start stop and step values
x.shape = (2, 5)  # now x is 2-dimensional
print(x[1, 3])
print(x[1, -1])
x[0][2]
# basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step (k!=0). This selects the m elements (in the corresponding dimension) with index values i,i+k,....



[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]
x:  [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
8
9


2

In [27]:
np.array(["hello", "world!"], dtype="U5")
np.array(["hello", "world!"], dtype="U7")

np.array(["hello", "world"], dtype="S7").tobytes()

b'hello\x00\x00world\x00\x00'

In [39]:

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
c = 3.0
# a * b
A = a + b
B = a - b
C = a / b
D = a % b
E = a // b
F = a ** c
# a & b
# a | b
print(A, B, C, D, E,F)



[3. 4. 5.] [-1.  0.  1.] [0.5 1.  1.5] [1. 0. 1.] [0. 1. 1.] [ 1.  8. 27.]
